/*
  - Date: 2018-03-11
  - Author: Joel
  - Purpose: Status code definitions
*/

/* DEFINITIONS */
typedef UINT32 KSTATUS;

#define STATUS_SUCCESS                        0x0000
#define STATUS_ERROR_UNKNOWN                  0x0001
#define STATUS_ERROR_OUT_OF_MEMORY            0x0002
#define STATUS_ERROR_OBJECT_DOES_NOT_EXIST    0x0003
#define STATUS_ERROR_UNABLE_TO_LOCK_OBJECT    0x0004
#define STATUS_ERROR_INSUFFICIENT_BUFER       0x0005
#define STATUS_ERROR_VALIDATION_CHECK_FAILED  0x0006
#define STATUS_ERROR_INVALID_FILE             0x0007
#define STATUS_ERROR_INVALID_DEVICE           0x0008
#define STATUS_ERROR_INVALID_REQUEST          0x0009
#define STATUS_ERROR_INVALID_HANDLE           0x000A
#define STATUS_ERROR_OBJECT_NOT_FOUND         0x000B

/* GLOBALS */

/* FUNCTIONS */
